name: Publish Docker image
on:
  push:
    branches: master
    tags:
      - "*"
  release:
    branches: master
    tags:
      - "*"
jobs:

  build:
    name: build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest

      - name: Login DockerHub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and Publish
        run: |
          TAGS=${{ github.repository }}:latest
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            TAGS="${TAGS} -t ${{ github.repository }}:${GITHUB_REF#refs/tags/v}"
          fi
          
          
          docker buildx build \
            --push \
            --platform linux/arm/v6,linux/arm/v7,linux/arm64,linux/amd64 \
            -t ${TAGS} .